enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[GooglePhotos]
build-mode = "apk"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
